// export const MUTATION_COMMIT = 'MUTATION_COMMIT'
// export const ACTION_COMMIT = 'ACTION_COMMIT'
const MUTATION_COMMIT = 'MUTATION_COMMIT'
const ACTION_COMMIT = 'ACTION_COMMIT'

export {MUTATION_COMMIT, ACTION_COMMIT}
